<a href="https://colab.research.google.com/github/abdumalikov443/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
print(pd.__version__)

2.2.3

In [23]:
my_dataset = {
    'cars': ['BMW', 'RR', 'Porsche', 'Tesla', 'Bugatti', 'Ford', 'BMW'],
    'counts': [3, 7, 2, 5, 4, 6, 3]
}

df = pd.DataFrame(my_dataset)
print(df)

      cars  counts
0      BMW       3
1       RR       7
2  Porsche       2
3    Tesla       5
4  Bugatti       4
5     Ford       6
6      BMW       3

In [10]:
df.head(10) # default 5 rows

      cars  counts
0      BMW       3
1       RR       7
2  Porsche       2
3    Tesla       5
4  Bugatti       4
5     Ford       6
6      BMW       9

In [11]:
df.tail() # default 5 rows

      cars  counts
2  Porsche       2
3    Tesla       5
4  Bugatti       4
5     Ford       6
6      BMW       9

In [12]:
df.shape

(7, 2)

In [13]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [14]:
df.dtypes

cars      object
counts     int64
dtype: object

In [16]:
df.describe() # numerical columns only

         counts
count  7.000000
mean   5.142857
std    2.410295
min    2.000000
25%    3.500000
50%    5.000000
75%    6.500000
max    9.000000

In [19]:
df.iloc[2:]

      cars  counts
2  Porsche       2
3    Tesla       5
4  Bugatti       4
5     Ford       6
6      BMW       9

In [20]:
df.loc[2, 'cars'] # ham row dan va column(label) lardan foydalanib ma'lumotlarni ko'rishni imkonini beradi

'Porsche'

In [26]:
print(df)

      cars  counts
0      BMW       3
1       RR       7
2  Porsche       2
3    Tesla       5
4  Bugatti       4
5     Ford       6
6      BMW       3

In [28]:
df[df['cars'] == 'BMW']

  cars  counts
0  BMW       3
6  BMW       3

In [29]:
# df.mean(numeric_only=True)
df['counts'].mean()

np.float64(4.285714285714286)

In [31]:
df['counts'].sum()

np.int64(30)

In [33]:
# df.min()
df.max()

cars      Tesla
counts        7
dtype: object

In [34]:
df.median(numeric_only=True) # middle value ni olib beradi

counts    4.0
dtype: float64

In [35]:
df.count() # dataset dagi non null value larni hisoblab chiqarib beradi

cars      7
counts    7
dtype: int64

In [36]:
df.std(numeric_only=True) #

counts    1.799471
dtype: float64

In [37]:
data_with_missing = {
    'cars': ['BMW', 'RR', 'Porsche', None, 'Bugatti', 'Ford', None],
    'counts': [3, 7, None, 5, None, 6, 12]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1       RR     7.0
2  Porsche     NaN
3     None     5.0
4  Bugatti     NaN
5     Ford     6.0
6     None    12.0

In [39]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [41]:
# df_missing.dropna(how='all')
df_missing.dropna(subset=['counts'])

   cars  counts
0   BMW     3.0
1    RR     7.0
3  None     5.0
5  Ford     6.0
6  None    12.0

In [42]:
df_missing.fillna({'cars': 'unknown', 'counts': 0})

      cars  counts
0      BMW     3.0
1       RR     7.0
2  Porsche     0.0
3  unknown     5.0
4  Bugatti     0.0
5     Ford     6.0
6  unknown    12.0

In [48]:
# df = pd.read_csv('Titanic-Dataset.csv')

df = pd.read_excel('output.xlsx')
df.head(30)
# df = pd.read_json('Titanic-Dataset.json')

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S

In [46]:
df.to_excel("output.xlsx")

In [49]:
# Series => 1D array lar bilan ishlashda qo'l keladi

cars = pd.Series(['BMW', 'RR', 'Porsche', 'Tesla'])
print(cars)

0        BMW
1         RR
2    Porsche
3      Tesla
dtype: object

In [52]:
car_series = data_with_missing['cars']
print(car_series)

['BMW', 'RR', 'Porsche', None, 'Bugatti', 'Ford', None]